#!/usr/bin/env bash

# This is a bash script to install my vim and bash preferences
# Inspiration drawn from @noopkat (https://raw.githubusercontent.com/noopkat/dotfiles/master/bin/vim-setup.sh)

BASE_DIR="$HOME/.vim"
PLUGIN_DIR="$BASE_DIR/bundle"
COLORS_DIR="$BASE_DIR/colors"
AUTOLOAD_DIR="$BASE_DIR/autoload"
PLUGINS=(
  "ctrlpvim/ctrlp.vim"
  "vim-airline/vim-airline"
  "vim-airline/vim-airline-themes"
  "scrooloose/nerdtree"
  "tpope/vim-pathogen"
  "terryma/vim-multiple-cursors"
  "airblade/vim-gitgutter"
  "Quramy/vim-js-pretty-template"
)

mkdir -p $PLUGIN_DIR
mkdir -p $COLORS_DIR
mkdir -p $AUTOLOAD_DIR

wget https://raw.githubusercontent.com/dracula/vim/master/colors/dracula.vim -O $COLORS_DIR/dracula.vim 
wget https://raw.githubusercontent.com/ntk148v/vim-horizon/master/colors/horizon.vim -O $COLORS_DIR/horizon.vim

for PLUGIN in ${PLUGINS[@]}; do
   DIRNAME="$(basename $PLUGIN)"
   git clone https://github.com/$PLUGIN.git $PLUGIN_DIR/$DIRNAME
done

cp $PLUGIN_DIR/vim-pathogen/autoload/pathogen.vim $AUTOLOAD_DIR/pathogen.vim


cp ./.vimrc ~/.vimrc
cp ./.bashrc ~/.bashrc

echo "All done!! (you may need to restart bash)"

